"""Using Stable Diffusion to generate images from a prompt."""
import keras_cv
import matplotlib.pyplot as plt

model = keras_cv.models.StableDiffusion(img_width=512, img_height=512)
generated_images = model.text_to_image("photograph of an astronaut riding a horse", batch_size=3)


def plot_images(images):
    """Plot the images that have been generated by stablediffusion.

    Args:
        images (List[Image]): the images that are to be plotted
    """
    plt.figure(figsize=(20, 20))
    for index, image in enumerate(images):
        plt.subplot(1, len(images), index + 1)
        plt.imshow(image)
        plt.axis("off")
        plt.show()


plot_images(generated_images)
